### ISSUE TITLE
Best selling - Get all products by purchase quantity limit 5, continuous scroll

### ISSUE THREAD

**Issue by raphdoo** [africommerce/africommerce-sass-backend#6]

**Comment by eddy1759** [comment]
I would like to work on this endpoint

what do you mean by continuous scroll @raphdoo @Skywonda

**Comment by eddy1759** [comment]
I would like to work on this endpoint

what do you mean by continuous scroll @raphdoo @Skywonda

**Comment by victoria-igbobi65** [comment]
I am interested in this
